### ISSUE TITLE
Example code for newBASICS_Data is outdated and now broken

### ISSUE THREAD

**Issue by s-andrews** [catavallejos/BASiCS#1]
The code in your BASiCSIntro.Rmd file says that you can create a test dataset with:

    set.seed(1)
    Counts = Counts = matrix(rpois(50*10, 2), ncol = 10)
    Tech = c(rep(FALSE,40),rep(TRUE,10))
    set.seed(2)
    SpikeInput = rgamma(10,1,1)
    
    # No batch effect
    DataExample = newBASiCS_Data(Counts, Tech, SpikeInput)

..but this no longer works.  The input for SpikeInput must now  be a data frame and not a vector.

A version which at least gets through as far as creating the data object would be:

    library(BASiCS)
    set.seed(1)
    Counts = Counts = matrix(rpois(50*10, 2), ncol = 10)
    rownames(Counts) <- 1:nrow(Counts)
    
    Tech = c(rep(FALSE,40),rep(TRUE,10))
    set.seed(2)
    
    SpikeInput <- data.frame(gene=rownames(Counts)[Tech],amount=rgamma(10,1,1))
    
    # No batch effect
    DataExample = newBASiCS_Data(Counts, Tech, SpikeInput)

**Comment by catavallejos** [comment]
Dear Simon, 

Thanks for reporting this issue. Few months ago, we decided to modify the 'newBASiCS_Data' in order to avoid issues where the input numbers in 'SpikeInput' were not in agreement with the order of the genes in the 'Counts' matrix. Sadly, we missed out to modify the code in the corresponding documentation. This is now fixed (version 0.3.4). The new example code is as follows

```{r}
# Expression counts
set.seed(1)
Counts = Counts = matrix(rpois(50*10, 2), ncol = 10)
rownames(Counts) <- paste("Gene", 1:nrow(Counts))

# Technical information 
Tech = c(rep(FALSE,40),rep(TRUE,10))

# Spikes input number of molecules 
set.seed(2)
SpikeInput <- data.frame(gene=rownames(Counts)[Tech],amount=rgamma(10,1,1))

# Creating a BASiCS_Data object (no batch effect)
DataExample = newBASiCS_Data(Counts, Tech, SpikeInput)

# Creating a BASiCS_Data object (with batch effect)
BatchInfo = c(rep(1, 5), rep(2, 5))
DataExample = newBASiCS_Data(Counts, Tech, SpikeInput, BatchInfo)
``` 

Let me know if you have any issues. In case it helps, we have also prepared a tutorial which is now available at: https://github.com/catavallejos/TutorialBASiCS

Best,

Catalina
