### ISSUE TITLE
BASiCS_MCMC crashes R whenever I try to run more than 12 cells at once

### ISSUE THREAD

**Issue by dvzhukov** [catavallejos/BASiCS#11]
Hi Catalina,

Whenever I try to run the following command on any number of cells over 12:

`MCMC_Output <- BASiCS_MCMC(FilterData, N = 40000, Thin = 10, Burn = 20000, PrintProgress = FALSE,
                           positive = TRUE)`

It returns the following error and crashes R session (with pop-up message "R encountered a fatal error. The session was terminated"):

` --------------------------------------------------------------------------- `
` IMPORTANT: by default, the argument PriorDelta was set equal to 'gamma'. `
` When performing a differential over-dispersion test between two populations, `
` we recommend to change this value to PriorDelta = 'log-normal' `
` --------------------------------------------------------------------------- `
`negative factor estimates, re-run with 'positive=TRUE'--------------------- `
`MCMC sampler has been started: 40000 iterations to go.`
`--------------------------------------------------------------------`
`Something went wrong when updating mu 1`

Please help me pin-point the cause. I'm happy to provide any additional information.

**Comment by catavallejos** [comment]
Hi Dmitriy,

The error you encountered is due to the usage of ‘scran’ (http://bioconductor.org/packages/release/bioc/html/scran.html) in order to define starting points for the algorithm implemented in BASiCS (this is the default option). You can see some comments regarding small sample sizes when using scran here: https://support.bioconductor.org/p/82072/

I spoke to Aaron Lun (the developer of scran) and he suggested that this error is usually a sign for further quality control required. Typically, this is due to some cells with very low total counts which, in turn, results on near zero (true) size factors. 

Therefore, I'd suggest you to do some additional exploratory analysis of your data to see if this is the case. In particular, you should ensure to remove problematic cells with very low total count. 

Please try this and let me know how it goes!

Best

Catalina

**Comment by dvzhukov** [comment]
Thank you for the reply, Catalina. It really helped!
In my particular case, I ended up having to remove all cells that had <20k mapped reads to get BASiCS_MCMC to run with higher number of cells.
