### ISSUE TITLE
Store chain parameters in BASiCS_Chain object

### ISSUE THREAD

**Issue by Alanocallaghan** [catavallejos/BASiCS#60]
Currently the parameters used in `BASiCS_MCMC` are lost upon generation of the `BASiCS_Chain` object. This is generally not going to be an issue, but it does mean that if an object is saved to disk, on loading it there is no way of knowing what the parameters were, unless the generating code is known and available. It would be straightforward to store these in another slot.

**Comment by catavallejos** [comment]
Hi Alan. Indeed, currently the `BASiCS_Chain` class does not contain any information about which parameters were used when running `BASiCS_MCMC`. Said this, some information is implicit. For example, you can know which option you used for `WithSpikes` and `Regression` by looking at which parameters are contained in the chain (e.g. `epsilon` only exists when `Regression = TRUE`). Of course, this does not cover all parameters. What else do you think is relevant?

In principle we could add extra slots. However, @nilseling and I went through a similar issue when extending to the regression case and decided that it's best not to alter the slots so that the `BASiCS_Chain` class and related methods are compatible across multiple versions the library. That's why we now store all MCMC draws as a list into a single `parameters` slot. Depending on what additional information you would like to include, we could include this within the same slot (although this would require modifying the `Summary` and other methods, which currently are applied to all elements of the `parameters` slot). Alternatively, we could save additional parameters into a separate output file (e.g. .txt). However, I am not sure whether either option is optimal.

@nilseling what do you think?

**Comment by Alanocallaghan** [comment]
The main utility I see would be in performing some level of post-mortem on the performance of the sampling process. For example, the N/Thin/Burn arguments are lost after running the chain (again assuming the code used isn't known).

As for where to store them, saving the parameters of the model separately to the parameters of the MCMC chain (or original function call) would make most sense. This shouldn't really break backwards compatibility, since one could store the used options in an `arguments` slot, then simply check for them during the `print` method, eg:

```
setMethod("print"[...] {
  [...]
  if (!is.null(x@arguments)) {
    [print options used]
  }
})
```

**Comment by Alanocallaghan** [comment]
On reflection, I don't know if this is worth it at the moment. Might be worth considering if the class is going to be expanded further, or if it could be made general enough to allow whatever future changes are needed. However I've shown a couple of examples below.
``` r
## Create dummy class
setClass("Person", 
    representation(
        name = "character", 
        age = "numeric"
    )
)

## Create instance
p <- new("Person", 
    name = "Alan", 
    age = 28
)
## Test and save to disk, then delete
show(p)
#> An object of class "Person"
#> Slot "name":
#> [1] "Alan"
#> 
#> Slot "age":
#> [1] 28
saveRDS(p, "tmp.rds")
rm(p)

## Update class to have extra slot
setClass("Person", 
    representation(
        name = "character", 
        age = "numeric", 
        address = "character"),
    prototype(address = "no fixed abode"))

## Reload old class
p <- readRDS("tmp.rds")
## Show will error because of a missing slot
show(p)
#> An object of class "Person"
#> Slot "name":
#> [1] "Alan"
#> 
#> Slot "age":
#> [1] 28
#> 
#> Slot "address":
#> Error in slot(object, what): no slot of name "address" for this object of class "Person"
## Check for the attribute in the show method
setMethod("show", 
    signature("Person"), 
    function(Person) {
        cat("I am", Person@name, "and I am", Person@age, "years old.\n") 
        ## Need to directly access the attribute because @address will error
        if (!is.null(attr(Person, "address"))) {
            cat("I live at", Person@address)
        }
    }
)
#> Warning: For function 'show', signature 'Person': argument in method
#> definition changed from (Person) to (object)
## Works now!
show(p)
#> I am Alan and I am 28 years old.
## Sadly, this will still cause problems...
validObject(p)
#> Error in validObject(p): invalid class "Person" object: slots in class definition but not in object: "address"

## Reset class definition
setClass("Person", 
    representation(
        name = "character", 
        age = "numeric"
    )
)


## Alternatively make a subclass
setClass("HousedPerson", 
    contains = "Person",
    representation(address = "character"),
    prototype(address = "no fixed abode"))

setMethod("show", 
    signature("Person"), 
    function(Person) {
        cat("I am", Person@name, "and I am", Person@age, "years old.\n") 
    }
)
#> Warning: For function 'show', signature 'Person': argument in method
#> definition changed from (Person) to (object)
setMethod("show", 
    signature("HousedPerson"), 
    function(Person) {
        cat("I am", Person@name, "and I am", Person@age, "years old.\n") 
        cat("I live at", Person@address, "\n")
    }
)
#> Warning: For function 'show', signature 'HousedPerson': argument in method
#> definition changed from (Person) to (object)

show(p)
#> I am Alan and I am 28 years old.
p2 <- new("HousedPerson", name = "Rory", age = 32, address = "Lenagh")
show(p2)
#> I am Rory and I am 32 years old.
#> I live at Lenagh
```

<sup>Created on 2018-10-18 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by catavallejos** [comment]
Thanks Alan. I agree, let's leave this as stand-by for now. I think it's good to wait until we have worked in the extended model (multi-donor), before making big changes to the class.

**Comment by Alanocallaghan** [comment]
See #38
