### ISSUE TITLE
BASiCS_Sim requires spikes

### ISSUE THREAD

**Issue by Alanocallaghan** [catavallejos/BASiCS#74]
It would be nice to make BASiCS_Sim not require the presence of spikes, since the BASiCS model no longer requires it. It would also be fairly straightforward to implement generation of batches (recursively calling BASiCS_Sim would be the quickest way)

**Comment by catavallejos** [comment]
Fixed in the devel branch: https://github.com/catavallejos/BASiCS/commit/530ccaa19f26e5d08f40259be298ee6493bef2d8 + https://github.com/catavallejos/BASiCS/commit/6ee9130f6f69c5b80251347ef71ab9e2ab4dd159

@Alanocallaghan could you please check it works well? I can then merge with master and bioc-devel.

**Comment by Alanocallaghan** [comment]
Will do

**Comment by catavallejos** [comment]
Extra changes in https://github.com/catavallejos/BASiCS/commit/cc1505229fcc7ef2947659edc7750d45b195da58
