### ISSUE TITLE
Can not install BASiCS for R 3.3.0 x64 on Win 10

### ISSUE THREAD

**Issue by curtis90** [catavallejos/BASiCS#8]
* preparing 'BASiCS':
* checking DESCRIPTION meta-information ... OK
* cleaning src
* installing the package to build vignettes
* creating vignettes ...Warning: running command '"C:/Users/ycao6/DOCUME~1/R/R-33~1.0/bin/x64/Rscript" --vanilla --default-packages= -e "tools::buildVignettes(dir = '.', tangle = TRUE)"' had status 1
 ERROR
Warning in engine$weave(file, quiet = quiet, encoding = enc) :
  The vignette engine knitr::rmarkdown is not available, because the rmarkdown package is not installed. Please install it.
Error: processing vignette 'BASiCSIntro.Rmd' failed with diagnostics:
It seems you should call rmarkdown::render() instead of knitr::knit2html() because BASiCSIntro.Rmd appears to be an R Markdown v2 document.
Execution halted
Error: Command failed (1)

**Comment by catavallejos** [comment]
Sad to hear the installation failed. The message you pasted in your comment suggests the issue is that rmarkdown is not available in your R session. Could you please check if you have it installed? Please let me know if the installation still fails after you install rmarkdown (if you don't have it previously installed).

**Comment by curtis90** [comment]
Okay, it works.

**Comment by catavallejos** [comment]
Great! Thanks for letting me know!
